apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minecraft-server-azure
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-server-azure
    spec:
      volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: minecraft-data
          readOnly: false
      containers:
      - name: minecraft-server-azure
        image: openhack/minecraft-server:2.0
        ports:
        - containerPort: 25565
          name: server
        - containerPort: 25575
          name: rcon
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - name: azure
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-azure
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 25565
  - name: rcon
    port: 25575
  selector:
    app: minecraft-server-azure
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
  location: westeurope
  storageAccount: team13storageaccount
