apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: dGVhbTEzc3RvcmFnZWFjY291bnQ=
  azurestorageaccountkey: bGhYR0RWS3hOQWtXWC96RE1yK0k2OVhKcGsvR1VIeE5XYVpFQXNlVXJvcGFGdFR3MjJBR2tYYnB5YnNSc2o5TVpDM1hwK3RTWlZhakI4ZHcyUWxPNEE9PQ==
